=== miguelemosreverte/PDCFinal/XML/WebContent/WEB-INF/xml/alumnos.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="alumnos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="alumno" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="alumno">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="apellido" minOccurs="1" maxOccurs="1" />
                <xs:element name="nombre"   minOccurs="0" maxOccurs="1" />
                <xs:element name="carreras" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
   
    <xs:element name="apellido" type="xs:string" />

    <xs:element name="nombre" type="xs:string" />

    <xs:element name="carreras">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="carrera" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="carrera">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="plan"    type="xs:integer" use="required" />
                    <xs:attribute name="periodo" type="xs:string"  use="optional" />
                </xs:extension>
            </xs:simpleContent>    
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== miguelemosreverte/PDCFinal/XML/WebContent/WEB-INF/xml/alumnos.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<alumnos xmlns="http://www.w3schools.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="./alumnos.xsd">
    <alumno>
        <apellido>Apellido1</apellido>
        <nombre>Nombre1</nombre>
        <carreras>
            <carrera plan="2003" periodo="201401">ING. INF</carrera>
        </carreras>
    </alumno>
    <alumno>
        <apellido>Apellido2</apellido>
        <nombre>Nombre2</nombre>
        <carreras>
            <carrera plan="2009" periodo="201102">ABOGACIA</carrera>
        </carreras>
    </alumno>
    <alumno>
        <apellido>Apellido3</apellido>
        <nombre>Nombre3</nombre>
        <carreras>
            <carrera plan="2008" periodo="201401">CONTADOR PÚBLICO</carrera>
            <carrera plan="2010" periodo="201301">NOTARIADO</carrera>
        </carreras>
    </alumno>
    <alumno>
        <apellido>Apellido4</apellido>
        <nombre>Nombre4</nombre>
        <carreras>
            <carrera plan="2003" periodo="201201">ING. INF</carrera>
        </carreras>
    </alumno>
    <alumno>
    	<apellido>Apellido5</apellido>
    	<carreras>
    		<carrera plan="2010">LIC. ADM.</carrera>
    	</carreras>
    </alumno>
</alumnos>
