=== miguelemosreverte/PDCFinal/XML1/WebContent/WEB-INF/xml/areas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="areas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="area" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="area">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="codigo" minOccurs="1" maxOccurs="1" />
                <xs:element name="nombre" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
   
    <xs:element name="codigo" type="xs:string" />

    <xs:element name="nombre" type="xs:string" />

</xs:schema>

=== miguelemosreverte/PDCFinal/XML1-Grupos/WebContent/WEB-INF/xml/areas.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<areas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	     xsi:noNamespaceSchemaLocation="./areas.xsd">
    <area>
        <codigo>ADM</codigo>
        <nombre>Administración</nombre>
    </area>
    <area>
        <codigo>BE</codigo>
        <nombre>Bedelía</nombre>
    </area>
    <area>
        <codigo>CO</codigo>
        <nombre>Comunicación Institucional</nombre>
    </area>
    <area>
        <codigo>DH</codigo>
        <nombre>Desarrollo Humano</nombre>
    </area>
</areas>
